### ISSUE TITLE
Add on not working

### ISSUE THREAD

**Issue by krisfawcett** [innova-apps/QR-Code-Generator-Add-On-for-Google-Spreadsheets#10]
The add on is not working. 
![Screenshot (14)](https://user-images.githubusercontent.com/58607048/70347884-7c876900-182f-11ea-9add-666658fd13b9.png)

**Comment by innova-apps** [comment]
If you use free version of the add-on you can generate only 20 QR codes per hour. Wait till the quote resets then you can generate another 20 QR codes.
