### ISSUE TITLE
drive.google.com refused to connect

### ISSUE THREAD

**Issue by mhudson10** [innova-apps/QR-Code-Generator-Add-On-for-Google-Spreadsheets#14]
Can you tell me why I'm getting this message when I try to open the generator?

**Comment by asysyarifmasjid** [comment]
how solve this issue: -

drive.google.com is blocked
drive.google.com refused to connect.

ERR_BLOCKED_BY_RESPONSE

**Comment by innova-apps** [comment]
Looks like connectivity / firewall issue on your side.
